Update Commit.yml

diff --git a/.github/workflows/Commit.yml b/.github/workflows/Commit.yml
--- a/.github/workflows/Commit.yml
+++ b/.github/workflows/Commit.yml
@@ -40,9 +40,14 @@ jobs:
 
       - name: Generate Changelog
         run: |
+          if [ -n "$PREVIOUS_SHA" ]; then
             git log "$PREVIOUS_SHA..$CURRENT_SHA" --pretty=format:"%h - %s" > changelog.txt
             echo "Changelog generated:"
             cat changelog.txt
+          else
+            echo "Previous commit SHA is not available. Cannot generate changelog."
+            exit 1
+          fi
  
       - name: Save Current Commit SHA
         run: |
