Update Push_artifact_to_confluence.yml

diff --git a/.github/workflows/Push_artifact_to_confluence.yml b/.github/workflows/Push_artifact_to_confluence.yml
--- a/.github/workflows/Push_artifact_to_confluence.yml
+++ b/.github/workflows/Push_artifact_to_confluence.yml
@@ -128,14 +128,26 @@ jobs:
            
           # Upload the file as an attachment
           RESPONSE=$(curl -u $USER_NAME:$AUTH_API_TOKEN \
-             -X POST \
-             -H "X-Atlassian-Token: nocheck" \
-             -F "file=@${ATTACHMENT_FILE_NAME}" \
-             -F "comment=File attached via GitHub Actions" \
-             "${CONFLUENCE_BASE_URL}/rest/api/content/${CONFLUENCE_PAGE_ID}/child/attachment")
-           
+          -X POST \
+          -H "X-Atlassian-Token: nocheck" \
+          -F "file=@${ATTACHMENT_FILE_NAME}" \
+          -F "comment=File attached via GitHub Actions" \
+          "${CONFLUENCE_BASE_URL}/rest/api/content/${CONFLUENCE_PAGE_ID}/child/attachment")
+
+          echo " Response: $RESPONSE"
+             
           ATTACHMENT_TITLE=$(echo $RESPONSE | jq -r '.results[0].title')
-          ATTACHMENT_LINK="${CONFLUENCE_BASE_URL}/wiki/download/attachments/${CONFLUENCE_PAGE_ID}/${ATTACHMENT_TITLE}"
+          
+          # Check if the title was extracted
+          if [ -z "$ATTACHMENT_TITLE" ]; then
+            echo "Error: Unable to extract attachment title."
+            exit 1
+          else
+            ATTACHMENT_LINK="${CONFLUENCE_BASE_URL}/wiki/download/attachments/${CONFLUENCE_PAGE_ID}/${ATTACHMENT_TITLE}"
+            echo "Attachment URL: ${ATTACHMENT_LINK}"
+            echo "ATTACHMENT_LINK=$ATTACHMENT_LINK" >> $GITHUB_ENV
+          fi
+                
 
           
       - name: Print
